/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package concurrent;

public class App {

    /*
    private static boolean ready;
    private static int number;

    private static class Reader extends Thread {
        @Override
        public void run() {
            while(!ready)
                Thread.yield();
            System.out.println("Reader Thread " + number);
        }
    }

    public static void main(String[] args) throws InterruptedException {
        new Reader().start();
        Thread.sleep(2000);
        number = 100;
        ready = true;
        System.out.println("Main Thread " + number);
    }
    */
    public static void main(String[] args) {
        Source sr = Source.newInstance(new EventData());
    }
}
